# Generated by Django 3.1.4 on 2020-12-06 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_task_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.ManyToManyField(blank=True, related_name='important', to=settings.AUTH_USER_MODEL),
        ),
    ]
