# Generated by Django 3.1.4 on 2020-12-13 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201206_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.ManyToManyField(blank=True, default=None, related_name='important', to=settings.AUTH_USER_MODEL),
        ),
    ]
